90 add and configure spacewalk pallets for amplitude runtime
pendulum-chain/pendulum pull request #109
Opened 2023-02-07 12:16 UTC by b-yap

this needs https://github.com/pendulum-chain/pendulum/pull/91.

2023-02-08 10:48 UTC, b-yap commented on node/src/chain_spec.rs
> +			batching_api: b"http://localhost:8070/currencies".to_vec(),
so @cr4pt0 , is this `vec![]` instead?

2023-02-09 10:13 UTC, ebma requested changes

2023-02-09 10:13 UTC, ebma commented on node/src/chain_spec.rs
> +			limit_volume_currency_id: XCM(DOT),
So we would need to set the amount to 900 units (maybe use the .one() function of a currency to take into account the decimals, ie. `SomeCurrency.one().mul(900)`). And for the `limit_volume_currency_id` we might want to actually use our wrapped USDC asset.

2023-02-09 10:13 UTC, ebma commented on node/src/chain_spec.rs
> +			coin_infos_map: vec![],
This has to change but I'm not yet sure to what.

2023-02-09 12:22 UTC, cr4pt0 approved these changes

2023-02-13 12:51 UTC, b-yap commented
Closing this one. proceed to PR https://github.com/pendulum-chain/pendulum/pull/116

2023-02-13 12:51 UTC, closed without merging